# Generated by Django 4.1.7 on 2023-05-06 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categorydb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=200, null=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='')),
                ('Description', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
